import { existsSync } from 'node:fs'
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { spawn } from 'node:child_process'
import sponsorPoliciesConfig from '../../../policies'
import { parseOnaraConfigText } from '../../core/config'
import { loadPolicies } from '../../policy'

const API_DIR = resolve(import.meta.dir, '../../..')
const POLICIES_INDEX = join(API_DIR, 'policies', 'index.ts')
const WORKER_ENTRYPOINT = 'src/adapters/cloudflare/worker.ts'

function parseArgs(args: string[]): { configDir: string | null; dryRun: boolean } {
  const idx = args.indexOf('--config')
  const configDir =
    idx === -1 || idx + 1 >= args.length ? null : resolve(args[idx + 1]!)
  return { configDir, dryRun: args.includes('--dry-run') }
}

function loadEnvFile(configDir: string): Record<string, string> {
  const vars: Record<string, string> = {}
  for (const dir of [configDir, dirname(configDir), dirname(dirname(configDir))]) {
    const envPath = join(dir, '.env')
    if (!existsSync(envPath)) continue
    const content = require('fs').readFileSync(envPath, 'utf-8')
    for (const line of content.split('\n')) {
      const trimmed = line.trim()
      if (!trimmed || trimmed.startsWith('#')) continue
      const eq = trimmed.indexOf('=')
      if (eq === -1) continue
      const key = trimmed.slice(0, eq)
      let value = trimmed.slice(eq + 1)
      if (
        (value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))
      ) {
        value = value.slice(1, -1)
      }
      if (!(key in vars)) vars[key] = value
    }
  }
  return vars
}

async function loadExternalDeployment(configDir: string): Promise<{
  policies: unknown[]
  wranglerConfig: string
}> {
  const onaraConfigPath = join(configDir, 'config.json')
  const wranglerConfig = join(configDir, 'wrangler.jsonc')
  if (!existsSync(onaraConfigPath)) {
    throw new Error(`Onara config not found: ${onaraConfigPath}`)
  }
  if (!existsSync(wranglerConfig)) {
    throw new Error(`Cloudflare Wrangler config not found: ${wranglerConfig}`)
  }

  const config = parseOnaraConfigText(await readFile(onaraConfigPath, 'utf-8'))
  loadPolicies(config.policies)
  return {
    policies: config.policies,
    wranglerConfig,
  }
}

function generatePoliciesIndex(policies: unknown[]): string {
  return `// Auto-generated by the Cloudflare deploy adapter — do not edit\nconst sponsorPolicies = ${JSON.stringify(policies, null, 2)}\n\nexport default sponsorPolicies\n`
}

function run(
  cmd: string,
  args: string[],
  cwd: string,
  env?: Record<string, string>,
): Promise<void> {
  return new Promise((resolvePromise, reject) => {
    const child = spawn(cmd, args, {
      cwd,
      stdio: 'inherit',
      env: { ...process.env, ...env },
    })
    child.on('close', (code) => {
      if (code === 0) resolvePromise()
      else reject(new Error(`${cmd} exited with code ${code}`))
    })
  })
}

async function main() {
  const { configDir, dryRun } = parseArgs(process.argv.slice(2))
  if (!configDir) {
    console.log(`${dryRun ? 'Validating' : 'Deploying'} Cloudflare adapter with in-tree policies...`)
    loadPolicies(sponsorPoliciesConfig)
    const args = [
      'wrangler',
      'deploy',
      '--minify',
      '--config',
      'adapters/cloudflare/wrangler.jsonc',
    ]
    if (dryRun) args.push('--dry-run')
    await run('npx', args, API_DIR)
    return
  }

  console.log(`${dryRun ? 'Validating' : 'Deploying'} Cloudflare adapter: ${configDir}`)
  const deployment = await loadExternalDeployment(configDir)
  const envVars = loadEnvFile(configDir)
  const originalIndex = await readFile(POLICIES_INDEX, 'utf-8')
  let indexWritten = false
  try {
    const generatedIndex = generatePoliciesIndex(deployment.policies)
    indexWritten = true
    await writeFile(POLICIES_INDEX, generatedIndex)
    console.log('Generated policies/index.ts.')

    const args = [
      'wrangler',
      'deploy',
      WORKER_ENTRYPOINT,
      '--minify',
      '--config',
      deployment.wranglerConfig,
    ]
    if (dryRun) args.push('--dry-run')
    await run('npx', args, API_DIR, envVars)
    console.log(dryRun ? 'Deploy validation complete.' : 'Deploy complete.')
  } finally {
    if (indexWritten) {
      await writeFile(POLICIES_INDEX, originalIndex)
      console.log('Restored policies/index.ts.')
    }
  }
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error))
  process.exit(1)
})
