import { z } from 'zod'
import { loadPolicies, type CompiledPolicies } from '../src/policy'

type JsonObject = Record<string, unknown>

const unifiedDeploymentConfigSchema = z
  .object({
    version: z.literal(1),
    wrangler: z.record(z.string(), z.unknown()),
    policies: z.array(z.unknown()).min(1),
  })
  .strict()

export type UnifiedDeploymentConfig = z.infer<
  typeof unifiedDeploymentConfigSchema
>

export type ResolvedUnifiedDeploymentConfig = {
  version: 1
  wrangler: JsonObject
  policies: unknown[]
  compiledPolicies: CompiledPolicies
  dynamicAuthorizationRequirementNames: string[]
}

function isRecord(value: unknown): value is JsonObject {
  return value !== null && typeof value === 'object' && !Array.isArray(value)
}

function validateWranglerConfig(
  wrangler: JsonObject,
  signingKeyEnvs: Set<string>,
): void {
  for (const field of ['name', 'main', 'compatibility_date']) {
    if (typeof wrangler[field] !== 'string' || wrangler[field].length === 0) {
      throw new Error(`Unified deployment wrangler.${field} is required.`)
    }
  }
  if (!/^\d{4}-\d{2}-\d{2}$/.test(wrangler.compatibility_date as string)) {
    throw new Error(
      'Unified deployment wrangler.compatibility_date must be YYYY-MM-DD.',
    )
  }

  const vars = wrangler.vars
  if (vars !== undefined && !isRecord(vars)) {
    throw new Error('Unified deployment wrangler.vars must be an object.')
  }

  for (const [name, value] of Object.entries(vars ?? {})) {
    if (
      signingKeyEnvs.has(name) ||
      /(?:_PRIVATE_KEY|_SIGNING_KEY|_MNEMONIC|_SECRET)$/.test(name)
    ) {
      throw new Error(
        `Secret-like binding ${name} must be provisioned as a Worker secret, not wrangler.vars.`,
      )
    }
    if (typeof value === 'string' && value.includes('suiprivkey1')) {
      throw new Error(
        `Private key material is forbidden in public Wrangler config (${name}).`,
      )
    }
  }

  if ('policies' in wrangler) {
    throw new Error(
      'policies belongs at the unified config top level, not inside wrangler.',
    )
  }
}

export function parseUnifiedDeploymentConfig(
  input: unknown,
): ResolvedUnifiedDeploymentConfig {
  const parsed = unifiedDeploymentConfigSchema.safeParse(input)
  if (!parsed.success) {
    const issue = parsed.error.issues[0]
    const path = issue?.path.length ? `${issue.path.join('.')}: ` : ''
    throw new Error(
      `Invalid unified deployment config: ${path}${issue?.message ?? 'unknown error'}`,
    )
  }

  const compiledPolicies = loadPolicies(parsed.data.policies)
  const dynamicAuthorizationRequirements = compiledPolicies.require.filter(
    (requirement) => requirement.enabled,
  )
  const dynamicAuthorizationRequirementNames =
    dynamicAuthorizationRequirements.map(
      (requirement) => requirement.name,
    )
  const signingKeyEnvs = new Set(
    dynamicAuthorizationRequirements.map(
      (requirement) => requirement.check.signingKeyEnv,
    ),
  )
  validateWranglerConfig(parsed.data.wrangler, signingKeyEnvs)

  return {
    version: 1,
    wrangler: parsed.data.wrangler,
    policies: parsed.data.policies,
    compiledPolicies,
    dynamicAuthorizationRequirementNames,
  }
}

export function parseUnifiedDeploymentConfigText(
  text: string,
): ResolvedUnifiedDeploymentConfig {
  let input: unknown
  try {
    input = JSON.parse(text)
  } catch (error) {
    throw new Error(
      `Invalid unified deployment config JSON: ${error instanceof Error ? error.message : String(error)}`,
    )
  }
  return parseUnifiedDeploymentConfig(input)
}

export function generatePoliciesIndex(policies: unknown[]): string {
  const json = JSON.stringify(policies, null, 2)
  return `// Auto-generated by deploy script — do not edit\nconst sponsorPolicies = ${json}\n\nexport default sponsorPolicies\n`
}

export function generateWranglerConfig(wrangler: JsonObject): string {
  return `${JSON.stringify(wrangler, null, 2)}\n`
}
