import { readdir, readFile, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import { spawn } from 'node:child_process'

const API_DIR = resolve(import.meta.dir, '..')
const POLICIES_INDEX = join(API_DIR, 'policies', 'index.ts')

function parseArgs(args: string[]): { configDir: string | null } {
  const idx = args.indexOf('--config')
  if (idx === -1 || idx + 1 >= args.length) return { configDir: null }
  return { configDir: resolve(args[idx + 1]!) }
}

async function readPolicies(dir: string): Promise<unknown[]> {
  const files = (await readdir(dir)).filter((f) => f.endsWith('.json')).sort()
  if (files.length === 0) {
    throw new Error(`No policy JSON files found in ${dir}`)
  }
  const policies: unknown[] = []
  for (const file of files) {
    const content = await readFile(join(dir, file), 'utf-8')
    policies.push(JSON.parse(content))
  }
  console.log(`Loaded ${files.length} policy file(s): ${files.join(', ')}`)
  return policies
}

function generateIndex(policies: unknown[]): string {
  const json = JSON.stringify(policies, null, 2)
  return `// Auto-generated by deploy script — do not edit\nconst sponsorPolicies = ${json}\n\nexport default sponsorPolicies\n`
}

function run(cmd: string, args: string[], cwd: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const child = spawn(cmd, args, { cwd, stdio: 'inherit' })
    child.on('close', (code) => {
      if (code === 0) resolve()
      else reject(new Error(`${cmd} exited with code ${code}`))
    })
  })
}

async function main() {
  const { configDir } = parseArgs(process.argv.slice(2))

  if (!configDir) {
    // Default: deploy with in-tree config
    console.log('Deploying with in-tree config...')
    await run('npx', ['wrangler', 'deploy', '--minify'], API_DIR)
    return
  }

  console.log(`Deploying with external config: ${configDir}`)

  const policiesDir = join(configDir, 'policies')
  const wranglerConfig = join(configDir, 'wrangler.jsonc')

  // Read and generate policies
  const policies = await readPolicies(policiesDir)
  const generatedIndex = generateIndex(policies)

  // Save original index.ts for restore
  const originalIndex = await readFile(POLICIES_INDEX, 'utf-8')

  try {
    // Write generated index
    await writeFile(POLICIES_INDEX, generatedIndex)
    console.log('Generated policies/index.ts')

    // Deploy — use --cwd so wrangler resolves the entry point relative to API_DIR
    // even when the config file lives in an external directory
    await run('npx', ['wrangler', 'deploy', '--minify', '--config', wranglerConfig, '--cwd', API_DIR], API_DIR)
    console.log('Deploy complete.')
  } finally {
    // Restore original
    await writeFile(POLICIES_INDEX, originalIndex)
    console.log('Restored policies/index.ts')
  }
}

main().catch((err) => {
  console.error(err.message)
  process.exit(1)
})
