import { describe, expect, test } from 'bun:test'
import {
  generatePoliciesIndex,
  generateWranglerConfig,
  parseUnifiedDeploymentConfig,
  parseUnifiedDeploymentConfigText,
} from './deployment-config'

const IDENTITY =
  '0x29dfbf688abce7ab43bb8e70cae158ae961196e721440f515482f8ba1684390f'

function requirement(name = 'miso-sender'): Record<string, unknown> {
  return {
    type: 'require',
    name,
    check: {
      kind: 'sender.dynamic',
      url: 'https://api.testnet.miso.fm/v1/onara/authorize',
      audience: 'miso-onara-authorization',
      signingKeyEnv: 'MISO_ONARA_SIGNING_KEY',
      signingIdentity: IDENTITY,
      timeoutMs: 1500,
      cacheTtlSeconds: 0,
    },
  }
}

function allow(
  name = 'purchase-record',
  requires = ['miso-sender'],
): Record<string, unknown> {
  return {
    type: 'allow',
    name,
    requires,
    commands: { allowed: ['MoveCall'], max: 1 },
    calls: {
      mode: 'sequence',
      rules: [{ id: 'purchase', targets: ['0x1::market::purchase'] }],
    },
  }
}

function config(
  policies: unknown[] = [requirement(), allow()],
): Record<string, unknown> {
  return {
    version: 1,
    wrangler: {
      name: 'miso-onara-testnet',
      main: 'src/workers.ts',
      compatibility_date: '2026-02-26',
      vars: { SUI_NETWORK: 'testnet' },
    },
    policies,
  }
}

describe('unified deployment config', () => {
  test('keeps flat policies and reports enabled dynamic requirements in source order', () => {
    const policies = [
      requirement('first'),
      allow('first-allow', ['first']),
      requirement('second'),
      allow('second-allow', ['second']),
    ]
    const parsed = parseUnifiedDeploymentConfig(config(policies))

    expect(parsed.policies).toEqual(policies)
    expect(parsed.dynamicRequirementNames).toEqual(['first', 'second'])
    expect(parsed.compiledPolicies.require).toHaveLength(2)
    expect(parsed.compiledPolicies.allow).toHaveLength(2)
  })

  test('disabled requirements remain strict but need not be referenced', () => {
    const disabled: Record<string, unknown> = {
      ...requirement(),
      enabled: false,
    }
    expect(
      parseUnifiedDeploymentConfig(config([disabled])).compiledPolicies.require[0]
        ?.enabled,
    ).toBe(false)

    expect(() =>
      parseUnifiedDeploymentConfig(
        config([
          {
            ...disabled,
            check: {
              ...(disabled.check as Record<string, unknown>),
              signingIdentity: 'UNCONFIGURED',
            },
          },
        ]),
      ),
    ).toThrow(/canonical Sui address/)
  })

  test('rejects reference registries and dynamic refs', () => {
    expect(() =>
      parseUnifiedDeploymentConfig({
        ...config(),
        requirements: { miso: {} },
      }),
    ).toThrow(/Unrecognized key.*requirements/)

    expect(() =>
      parseUnifiedDeploymentConfig(
        config([
          {
            type: 'require',
            name: 'bad',
            check: { ref: 'miso' },
          },
        ]),
      ),
    ).toThrow()
  })

  test('rejects secret values in public Wrangler vars', () => {
    expect(() =>
      parseUnifiedDeploymentConfig({
        ...config(),
        wrangler: {
          name: 'miso-onara-testnet',
          main: 'src/workers.ts',
          compatibility_date: '2026-02-26',
          vars: { MISO_ONARA_SIGNING_KEY: 'suiprivkey1not-public' },
        },
      }),
    ).toThrow(/must be provisioned as a Worker secret/)
  })

  test('strictly validates the envelope and Wrangler fields', () => {
    expect(() =>
      parseUnifiedDeploymentConfig({ ...config(), unexpected: true }),
    ).toThrow(/Unrecognized key.*unexpected/)
    expect(() =>
      parseUnifiedDeploymentConfig({
        ...config(),
        wrangler: { name: 'missing-fields' },
      }),
    ).toThrow(/wrangler\.main is required/)
    expect(() => parseUnifiedDeploymentConfigText('{')).toThrow(
      /Invalid unified deployment config JSON/,
    )
  })

  test('generates deterministic engine and Wrangler files', () => {
    const policies = [requirement(), allow()]
    expect(generatePoliciesIndex(policies)).toBe(
      `// Auto-generated by deploy script — do not edit\nconst sponsorPolicies = ${JSON.stringify(policies, null, 2)}\n\nexport default sponsorPolicies\n`,
    )
    expect(
      generateWranglerConfig({
        name: 'onara',
        main: 'src/workers.ts',
        compatibility_date: '2026-02-26',
      }),
    ).toBe(
      '{\n  "name": "onara",\n  "main": "src/workers.ts",\n  "compatibility_date": "2026-02-26"\n}\n',
    )
  })
})
