import { readdir, readFile, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { spawn } from 'node:child_process'

const API_DIR = resolve(import.meta.dir, '..')
const POLICIES_INDEX = join(API_DIR, 'policies', 'index.ts')

function parseArgs(args: string[]): { configDir: string | null } {
  const idx = args.indexOf('--config')
  if (idx === -1 || idx + 1 >= args.length) return { configDir: null }
  return { configDir: resolve(args[idx + 1]!) }
}

function loadEnvFile(configDir: string): Record<string, string> {
  const vars: Record<string, string> = {}
  for (const dir of [configDir, dirname(configDir), dirname(dirname(configDir))]) {
    const envPath = join(dir, '.env')
    if (!existsSync(envPath)) continue
    const content = require('fs').readFileSync(envPath, 'utf-8')
    for (const line of content.split('\n')) {
      const trimmed = line.trim()
      if (!trimmed || trimmed.startsWith('#')) continue
      const eq = trimmed.indexOf('=')
      if (eq === -1) continue
      const key = trimmed.slice(0, eq)
      let value = trimmed.slice(eq + 1)
      if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
        value = value.slice(1, -1)
      }
      if (!(key in vars)) vars[key] = value
    }
  }
  return vars
}

async function readPoliciesFromDir(dir: string): Promise<unknown[]> {
  const files = (await readdir(dir)).filter((f) => f.endsWith('.json')).sort()
  if (files.length === 0) {
    throw new Error(`No policy JSON files found in ${dir}`)
  }
  const policies: unknown[] = []
  for (const file of files) {
    const content = await readFile(join(dir, file), 'utf-8')
    policies.push(JSON.parse(content))
  }
  console.log(`Loaded ${files.length} policy file(s) from policies/: ${files.join(', ')}`)
  return policies
}

async function readPolicies(configDir: string): Promise<unknown[]> {
  const configJson = join(configDir, 'config.json')
  if (existsSync(configJson)) {
    const parsed = JSON.parse(await readFile(configJson, 'utf-8'))
    if (Array.isArray(parsed?.policies)) {
      console.log(`Loaded ${parsed.policies.length} policy entry(ies) from config.json`)
      return parsed.policies
    }
  }
  const policiesDir = join(configDir, 'policies')
  if (existsSync(policiesDir)) {
    return readPoliciesFromDir(policiesDir)
  }
  throw new Error(`No config.json with "policies" array or policies/ directory found in ${configDir}`)
}

function generateIndex(policies: unknown[]): string {
  const json = JSON.stringify(policies, null, 2)
  return `// Auto-generated by deploy script — do not edit\nconst sponsorPolicies = ${json}\n\nexport default sponsorPolicies\n`
}

function run(cmd: string, args: string[], cwd: string, env?: Record<string, string>): Promise<void> {
  return new Promise((resolve, reject) => {
    const child = spawn(cmd, args, { cwd, stdio: 'inherit', env: { ...process.env, ...env } })
    child.on('close', (code) => {
      if (code === 0) resolve()
      else reject(new Error(`${cmd} exited with code ${code}`))
    })
  })
}

async function main() {
  const { configDir } = parseArgs(process.argv.slice(2))

  if (!configDir) {
    // Default: deploy with in-tree config
    console.log('Deploying with in-tree config...')
    await run('npx', ['wrangler', 'deploy', '--minify'], API_DIR)
    return
  }

  console.log(`Deploying with external config: ${configDir}`)

  const wranglerConfig = join(configDir, 'wrangler.jsonc')
  const envVars = loadEnvFile(configDir)

  // Read and generate policies
  const policies = await readPolicies(configDir)
  const generatedIndex = generateIndex(policies)

  // Save original index.ts for restore
  const originalIndex = await readFile(POLICIES_INDEX, 'utf-8')

  try {
    // Write generated index
    await writeFile(POLICIES_INDEX, generatedIndex)
    console.log('Generated policies/index.ts')

    // Deploy — pass entry point as positional arg so wrangler resolves it
    // relative to cwd (API_DIR) rather than the external config file location
    await run('npx', ['wrangler', 'deploy', 'src/workers.ts', '--minify', '--config', wranglerConfig], API_DIR, envVars)
    console.log('Deploy complete.')
  } finally {
    // Restore original
    await writeFile(POLICIES_INDEX, originalIndex)
    console.log('Restored policies/index.ts')
  }
}

main().catch((err) => {
  console.error(err.message)
  process.exit(1)
})
